name: test_sl
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  mongo_dart: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/back_icon.png
    - assets/icons/menu_icon.png
    - assets/icons/Icon.png
    - assets/images/image.png
    - assets/icons/icon_heart.png
    - assets/images/image_56.png
    - assets/images/apple-icon.png
    - assets/img_dientich.png
    - assets/img_giohang.png
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png
    - assets/img_user_profile.png
    - assets/home.png
    - assets/chart.png
    - assets/bell.png
    - assets/user.png
